   [build]
     # Используем Node.js buildpack
     builder = "heroku/buildpacks:20"

   [deploy]
     # Команда для установки зависимостей
     install = "npm install"

     # Команда для запуска приложения
     start = "npm start"
